### ISSUE TITLE
I couldn't get the ttl to open in TopBraid CE...

### ISSUE THREAD

**Issue by smrgeoinfo** [dr-shorthair/ont#3]
```
Could not load \ProjectMetadata\project-ont\rdf\project.ttl or one of its imports.
The most recent URI was https://linked.data.gov.au/def/project
```

I tried various standard tricks to get it to work, no luck...
It will open in Protege...

**Comment by dr-shorthair** [comment]
If you set `Accept: text/turtle` in the HTTP headers it seems to work.

**Comment by smrgeoinfo** [comment]
I checked out the github repo and am trying to open the local copy in TopBraid.    ? I don't see a way to put in an accept header, doesn't the ttl file extension do that on the desktop?

**Comment by dr-shorthair** [comment]
Hmm. I have just tested what I think you describe and no problem: 
![image](https://github.com/dr-shorthair/project-ont/assets/608303/de670097-b612-4e83-be50-1ebe83cdee86)

**Comment by smrgeoinfo** [comment]
Yes, that's  what I'm doing, but gets an error message
```
Could not load \ProjectMetadata\project-ont\rdf\project.ttl or one of its imports.
The most recent URI was http://www.w3.org/2004/02/skos/core
```

must be something about my workspace.  I'll try a new empty workspace.

**Comment by smrgeoinfo** [comment]
I tried in a new, empty TBC workspace, same problem.  I'll just have to study this one using Protege, I can open the ttl with that.
